// Configuração — add players, "Sorteio Mágico de Duplas", edit dupla names,
// "GERAR CAMPEONATO". See CLAUDE.md §4A.
import { useRef, useState } from 'react'
import { UserPlus, X, Shuffle, Trophy, Users, Minus, Plus, GripVertical } from 'lucide-react'
import { uid, generateDoubleElim, CUPS_PER_TEAM } from '../engine.js'

// "Dupla N — X & Y" autogenerated name: keep the "Dupla N — " prefix, refresh the tail.
const DEFAULT_DUPLA_NAME = /^(Dupla \d+ — ).*/

const makeWOPlayer = () => ({ id: uid('wo'), name: 'Vaga (W.O.)', isWO: true })

function shuffle(arr) {
  const a = [...arr]
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[a[i], a[j]] = [a[j], a[i]]
  }
  return a
}

export default function Setup({ ctx }) {
  const { state, setState, go } = ctx
  const [name, setName] = useState('')
  // null = automatic (≈ players / 2). Number = operator-forced team count.
  const [targetDuplas, setTargetDuplas] = useState(null)
  // Manual dupla editing: drag a member chip onto another to swap them between
  // duplas. dragRef carries the dragged {duplaId, playerId}; `picked` is the
  // tap-to-swap fallback for touch screens (tap one chip, then tap another).
  const dragRef = useRef(null)
  const [picked, setPicked] = useState(null)

  const setTournamentName = (value) =>
    setState((s) => ({ ...s, tournamentName: value }))

  const addPlayer = () => {
    const n = name.trim()
    if (!n) return
    setState((s) => ({ ...s, players: [...s.players, { id: uid('p'), name: n }] }))
    setName('')
  }

  const removePlayer = (id) =>
    setState((s) => ({
      ...s,
      players: s.players.filter((p) => p.id !== id),
      duplas: [], // player list changed — invalidate draw
      bracket: null,
    }))

  // Rename a player in place (after roster set / Sorteio) without redoing the
  // draw. Refreshes any autogenerated "Dupla N — X & Y" tail so dupla labels
  // track the new name; operator-renamed duplas are left untouched.
  const renamePlayer = (id, value) =>
    setState((s) => {
      const players = s.players.map((p) => (p.id === id ? { ...p, name: value } : p))
      const nameById = Object.fromEntries(players.map((p) => [p.id, p.name]))
      const duplas = s.duplas.map((d) => ({
        ...d,
        name: d.name.replace(
          DEFAULT_DUPLA_NAME,
          (_, prefix) => prefix + d.playerIds.map((pid) => nameById[pid] || '—').join(' & '),
        ),
      }))
      return { ...s, players, duplas }
    })

  const sortear = () =>
    setState((s) => {
      const real = shuffle(s.players.filter((p) => !p.isWO))
      // How many teams to form. Default ≈ half the roster; operator can override.
      const n = Math.max(2, targetDuplas ?? Math.max(2, Math.round(real.length / 2)))
      // Spread players round-robin so teams stay even; remainder makes 3-player teams.
      const buckets = Array.from({ length: n }, () => [])
      real.forEach((p, i) => buckets[i % n].push(p))

      const phantoms = []
      const duplas = buckets.map((members, i) => {
        // Empty bucket → full W.O. dupla (becomes a bye). Lone player → W.O. partner.
        if (members.length === 0) {
          const a = makeWOPlayer()
          const b = makeWOPlayer()
          phantoms.push(a, b)
          members = [a, b]
        } else if (members.length === 1) {
          const w = makeWOPlayer()
          phantoms.push(w)
          members = [...members, w]
        }
        return {
          id: uid('d'),
          name: `Dupla ${i + 1} — ${members.map((m) => m.name).join(' & ')}`,
          playerIds: members.map((m) => m.id),
        }
      })

      return {
        ...s,
        players: [...real, ...phantoms],
        duplas,
        bracket: null,
      }
    })

  const renameDupla = (id, value) =>
    setState((s) => ({
      ...s,
      duplas: s.duplas.map((d) => (d.id === id ? { ...d, name: value } : d)),
    }))

  // Swap two members across (or within) duplas. Dupla ids are untouched, so a
  // generated bracket stays valid — only who plays for each dupla changes.
  const swapMembers = (a, b) => {
    if (!a || !b || a.playerId === b.playerId) return
    setState((s) => {
      const nameById = Object.fromEntries(s.players.map((p) => [p.id, p.name]))
      const duplas = s.duplas.map((d) => {
        if (d.id !== a.duplaId && d.id !== b.duplaId) return d
        const playerIds = d.playerIds.map((pid) =>
          pid === a.playerId ? b.playerId : pid === b.playerId ? a.playerId : pid,
        )
        // Refresh the autogenerated "Dupla N — X & Y" tail if untouched by operator.
        const name = d.name.replace(
          DEFAULT_DUPLA_NAME,
          (_, prefix) => prefix + playerIds.map((id) => nameById[id] || '—').join(' & '),
        )
        return { ...d, playerIds, name }
      })
      return { ...s, duplas }
    })
  }

  // A chip was activated (drop target or second tap). Resolve against pending source.
  const onChipActivate = (target, isWO) => {
    if (isWO) return
    const src = dragRef.current || picked
    if (src) {
      swapMembers(src, target)
      dragRef.current = null
      setPicked(null)
    } else {
      setPicked(target)
    }
  }

  const gerar = () =>
    setState((s) => {
      const { bracket } = generateDoubleElim(s.duplas)
      return {
        ...s,
        bracket,
        currentMatchId: null,
        cups: { left: CUPS_PER_TEAM, right: CUPS_PER_TEAM },
        undoStack: [],
        stats: { byPlayer: {} },
        champion: null,
      }
    })

  const realPlayers = state.players.filter((p) => !p.isWO)
  const playerById = Object.fromEntries(state.players.map((p) => [p.id, p]))
  const canSortear = realPlayers.length >= 3
  const canGerar = state.duplas.length >= 2

  const autoCount = Math.max(2, Math.round(realPlayers.length / 2))
  const effectiveCount = targetDuplas ?? autoCount
  const maxDuplas = Math.max(2, realPlayers.length) // each team could ride a W.O. seat
  const setCount = (n) => setTargetDuplas(Math.min(maxDuplas, Math.max(2, n)))

  return (
    <div className="space-y-8">
      <div className="flex items-center gap-4">
        <img
          src="/taca-logo.png"
          alt=""
          className="hidden sm:block h-24 w-auto shrink-0 drop-shadow-lg"
        />
        <SectionHead
          kicker="PASSO 1"
          title="Configuração"
          sub="Cadastre os jogadores, sorteie as duplas e gere o chaveamento."
        />
      </div>

      {/* Edition name */}
      <section className="rounded-xl border border-linha bg-mata-2 p-5 sm:p-6">
        <label htmlFor="edition-name" className="font-display text-xl text-gelo">
          Nome da Edição
        </label>
        <p className="font-mono text-[11px] text-gelo/50 mt-1 mb-3">
          Identifica o torneio no topo e no histórico. Opcional.
        </p>
        <input
          id="edition-name"
          value={state.tournamentName || ''}
          onChange={(e) => setTournamentName(e.target.value)}
          placeholder="Ex.: Taça Guaraná — Inverno 2026"
          className="w-full rounded-lg border border-linha bg-mata px-4 py-3 text-lg text-gelo
                     outline-none focus:border-dourado placeholder:text-gelo/30"
        />
      </section>

      {/* Player roster */}
      <section className="rounded-xl bg-fundo text-tinta p-5 sm:p-6">
        <div className="flex items-center gap-2 mb-4">
          <Users size={20} className="text-guarana" />
          <h3 className="font-display text-xl text-guarana">Jogadores</h3>
          <span className="font-mono text-sm text-inativo-tinta ml-auto">
            {realPlayers.length} no total
          </span>
        </div>

        <div className="flex gap-2">
          <input
            value={name}
            onChange={(e) => setName(e.target.value)}
            onKeyDown={(e) => e.key === 'Enter' && addPlayer()}
            placeholder="Nome do jogador"
            className="flex-1 rounded-lg border border-inativo bg-branco px-4 py-3 text-lg
                       outline-none focus:border-guarana"
          />
          <button
            onClick={addPlayer}
            className="flex items-center gap-2 rounded-lg bg-guarana px-5 py-3 font-bold
                       text-branco hover:bg-guarana/90 active:scale-95 transition"
          >
            <UserPlus size={20} /> Adicionar
          </button>
        </div>

        {realPlayers.length === 0 ? (
          <p className="mt-4 text-inativo-tinta">Nenhum jogador ainda. Adicione o primeiro acima.</p>
        ) : (
          <ul className="mt-4 flex flex-wrap gap-2">
            {realPlayers.map((p) => (
              <li
                key={p.id}
                className="flex items-center gap-2 rounded-full bg-inativo px-3 py-1.5 text-tinta"
              >
                <input
                  value={p.name}
                  onChange={(e) => renamePlayer(p.id, e.target.value)}
                  aria-label={`Editar nome de ${p.name}`}
                  style={{ width: `${Math.max(4, p.name.length)}ch` }}
                  className="bg-transparent font-medium outline-none focus:text-guarana"
                />
                <button
                  onClick={() => removePlayer(p.id)}
                  aria-label={`Remover ${p.name}`}
                  className="text-inativo-tinta hover:text-copo"
                >
                  <X size={16} />
                </button>
              </li>
            ))}
          </ul>
        )}
      </section>

      {/* Draw */}
      <section className="rounded-xl border border-linha bg-mata-2 p-5 sm:p-6">
        {/* Team-count control: how many duplas the Sorteio should form. */}
        <div className="mb-4 flex items-center justify-between gap-3 rounded-lg bg-mata px-4 py-3">
          <div>
            <p className="font-display text-lg text-gelo leading-none">Número de Duplas</p>
            <p className="font-mono text-[11px] text-gelo/50 mt-1">
              {targetDuplas == null
                ? `Automático (${autoCount})`
                : `Definido pelo operador`}
            </p>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={() => setCount(effectiveCount - 1)}
              disabled={effectiveCount <= 2}
              aria-label="Menos duplas"
              className="h-11 w-11 flex items-center justify-center rounded-lg bg-mata-2 border border-linha
                         text-gelo enabled:hover:border-gelo/40 enabled:active:scale-95 transition
                         disabled:opacity-30"
            >
              <Minus size={20} />
            </button>
            <span className="font-mono font-bold text-3xl text-dourado w-12 text-center tabular-nums">
              {effectiveCount}
            </span>
            <button
              onClick={() => setCount(effectiveCount + 1)}
              disabled={effectiveCount >= maxDuplas}
              aria-label="Mais duplas"
              className="h-11 w-11 flex items-center justify-center rounded-lg bg-mata-2 border border-linha
                         text-gelo enabled:hover:border-gelo/40 enabled:active:scale-95 transition
                         disabled:opacity-30"
            >
              <Plus size={20} />
            </button>
            {targetDuplas != null && (
              <button
                onClick={() => setTargetDuplas(null)}
                className="ml-1 font-mono text-[11px] text-gelo/50 hover:text-gelo underline"
              >
                auto
              </button>
            )}
          </div>
        </div>

        <button
          onClick={sortear}
          disabled={!canSortear}
          className="w-full flex items-center justify-center gap-3 rounded-lg bg-copo px-6 py-4
                     font-display text-2xl text-branco shadow-lg shadow-copo/20
                     enabled:hover:bg-copo-glow enabled:active:scale-[0.99] transition
                     disabled:opacity-40 disabled:cursor-not-allowed"
        >
          <Shuffle size={26} /> Sorteio Mágico de Duplas
        </button>
        {!canSortear && (
          <p className="mt-2 text-center font-mono text-xs text-gelo/50">
            Mínimo 3 jogadores. Número ímpar ganha uma vaga W.O.
          </p>
        )}

        {state.duplas.length > 0 && (
          <>
            <p className="mt-5 mb-2 font-mono text-[11px] text-gelo/50">
              Arraste um jogador sobre outro para trocá-los de dupla — ou toque em um e depois no
              outro.
            </p>
            <ul className="grid gap-2 sm:grid-cols-2">
              {state.duplas.map((d, i) => (
                <li key={d.id} className="rounded-lg bg-mata px-3 py-2.5">
                  <div className="flex items-center gap-3">
                    <span className="font-mono text-dourado text-sm shrink-0">
                      {String(i + 1).padStart(2, '0')}
                    </span>
                    <input
                      value={d.name}
                      onChange={(e) => renameDupla(d.id, e.target.value)}
                      className="flex-1 bg-transparent text-gelo font-medium outline-none
                                 focus:text-branco"
                    />
                  </div>
                  <div className="mt-2 flex flex-wrap gap-1.5">
                    {d.playerIds.map((pid) => {
                      const p = playerById[pid]
                      const wo = !p || p.isWO
                      const target = { duplaId: d.id, playerId: pid }
                      const isPicked = picked?.playerId === pid
                      return (
                        <button
                          key={pid}
                          type="button"
                          draggable={!wo}
                          onDragStart={() => {
                            dragRef.current = target
                            setPicked(null)
                          }}
                          onDragEnd={() => {
                            dragRef.current = null
                          }}
                          onDragOver={(e) => !wo && e.preventDefault()}
                          onDrop={(e) => {
                            e.preventDefault()
                            onChipActivate(target, wo)
                          }}
                          onClick={() => onChipActivate(target, wo)}
                          className={[
                            'flex items-center gap-1.5 rounded-full px-2.5 py-1 text-sm transition',
                            wo
                              ? 'bg-mata-2 text-gelo/30 cursor-default'
                              : 'bg-mata-2 text-gelo cursor-grab active:cursor-grabbing hover:bg-mata-2/70',
                            isPicked ? 'ring-2 ring-dourado text-dourado' : '',
                          ].join(' ')}
                        >
                          {!wo && <GripVertical size={13} className="text-gelo/40 shrink-0" />}
                          <span className="truncate max-w-[10rem]">{p?.name || 'W.O.'}</span>
                        </button>
                      )
                    })}
                  </div>
                </li>
              ))}
            </ul>
          </>
        )}
      </section>

      {/* Generate */}
      <button
        onClick={() => {
          gerar()
          go('bracket')
        }}
        disabled={!canGerar}
        className="w-full flex items-center justify-center gap-3 rounded-xl
                   bg-dourado px-6 py-6 font-display text-3xl text-mata
                   enabled:hover:brightness-105 enabled:active:scale-[0.99] transition
                   disabled:opacity-30 disabled:cursor-not-allowed taca-gold"
      >
        <Trophy size={32} /> Gerar Campeonato
      </button>
      {!canGerar && (
        <p className="text-center font-mono text-xs text-gelo/50 -mt-4">
          Sorteie ao menos 2 duplas para gerar o chaveamento.
        </p>
      )}
    </div>
  )
}

export function SectionHead({ kicker, title, sub }) {
  return (
    <div>
      <p className="font-mono text-xs tracking-widest text-dourado">{kicker}</p>
      <h2 className="font-display text-4xl sm:text-5xl text-gelo mt-1">{title}</h2>
      {sub && <p className="text-gelo/60 mt-2 max-w-prose">{sub}</p>}
    </div>
  )
}
